name: "Pull Request Labeler"
on:
- pull_request_target
- workflow_dispatch

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
         pr-number: |
          14
          15
          17
          18
          19
          20
          21
          22
          23
          24
          26
          27
          28
          29
          30
          31
          32
          33
          34
          35
          36
          37
          38
          40
          41