name: "Pull Request Labeler"
on:
- pull_request_target
- workflow_dispatch

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
         pr-number: |
          68
          67
          66
          65
          64
          63
          61
          60
          59
          58
          57
          55
          54
          53
          52
          51
          50
          49
          48
          47
          46
          45
          44
          43
          42
          69
          70
          71
          72
          73
          74
          75
          76
          77
          78
          79
          80
          81
          82
          83
          84
          85
          86
          87
          88
          89
          90
          91
          92
          93